### ISSUE TITLE
Error while processing request

### ISSUE THREAD

**Issue by lazpap** [Azure/azure-mobile-apps-android-client#130]
My android client app suddenly can't connect to my web app any more. A Toast says "Error while processing request". In Android Studio debugger, I locate the error in MobileServiceConnection.java file.
java.io.IOException: stream was reset: PROTOCOL_ERROR
In Azure Portal, my app shows "Healthy" status, but I can see the HTTP errors. Please help.

**Comment by erikmompean** [comment]
Hi are you using Guava Futures Class for callbacks?
I m using it to login and callApi and i think that's because Futures.AddCallback is deprecated on Azure code. [Link here](https://google.github.io/guava/releases/22.0/api/docs/com/google/common/util/concurrent/Futures.html#addCallback-com.google.common.util.concurrent.ListenableFuture-com.google.common.util.concurrent.FutureCallback-)

**Comment by MatkovIvan** [comment]
Hi @lazpap 

It looks like that issue related to HTTP2 and coming from the underlying library.
I guess it _can_ be fixed by #122 which merged but has not yet been released.

PS Perhaps you already found the answer on [stackoverflow](https://stackoverflow.com/questions/49650333)

Best,
Ivan

**Comment by erikmompean** [comment]
I have the http20enabled on false and Okhttp updated to 3.9.0 and still not working. Any suggestions?

**Comment by lazpap** [comment]
For anyone facing the same problem, here is the **solution.**
or watch for other errors
Go to https://resources.azure.com/
Make sure you are in Read/Write mode by clicking in the option to the left of your name.
From the left column, browse to: https://resources.azure.com/subscriptions/yourSubscriptionId/resourceGroups/yourWebAppResourceGroup/providers/Microsoft.Web/sites/yourWebAppName/config/web
Find and Change the property: "http20Enabled": from true to false by clicking EDIT, Update value to “false” and then click Save or PATCH.
@erikmompean I use okttp 3.9.0 and it works fine. Try to restart your app or watch for other errors on Azure Portal.

**Comment by MatkovIvan** [comment]
Just checked it out with last release (`3.4.0`) and last `master`. I confirmed that updating Okhttp helps. But update a version in your gradle file isn't enough. Until a new issue is released, you can checkout SDK from `master` branch so it uses the new version.

**Comment by erikmompean** [comment]
I have all things configured exactly like @lazpap but nothing...
@MatkovIvan what *master* are you talking about? Azure or Okhttp?

Last week i've open a post on stackoverflow. [This is my code](https://stackoverflow.com/questions/49690586/error-while-processing-request-on-azure) if someone can take a look. 
Thanks anyway.

**Comment by MatkovIvan** [comment]
@erikmompean `master` branch in this repo.

**Comment by erikmompean** [comment]
@MatkovIvan I've downloaded master and it still not working... Any idea? Know you if azure is working on that as they said a week ago?

> Starting at 02:00 UTC on 3 Apr 2018, you have been identified as a customer using App Services who may have received connection failure notifications when using Android apps with older HTTP clients or desktop browsers using cross-site scripting calls. **Engineers have identified an issue with a recent deployment and are investigating mitigation options.**

**Comment by MatkovIvan** [comment]
@erikmompean
I perceive this topic as a request to update "Android apps with older HTTP clients" to properly support HTTP2 in Android Client SDK. This should be already done in `master` branch.
Since this error is gone during our tests, could you please share reproduction sample project to investigate exactly your case?

**Comment by MatkovIvan** [comment]
Well, the fix still isn't included in your project.
I see the usage of 3.4.0 SDK (not from `master` branch where it's fixed) in your gradle files.
Remove these lines:
```
compile 'com.microsoft.azure:azure-mobile-android:3.4.0@aar'
compile 'com.squareup.okhttp:okhttp:2.7.5'
```
Then add SDK from latest `master` as a module to your project and include it as a project dependency. This is a workaround to grab latest changes while next version of SDK isn't released.

Also, you have to update usage of `setAndroidHttpClientFactory` where you use an old client.

Best,
Ivan

**Comment by elamalani** [comment]
Closing this issue as @MatkovIvan helped resolve the error.
